spring:
  application:
    name: mycloset
  output:
    ansi:
      enabled: always

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mycloset?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: wnghWkd3835! #  실행환경에서 알아서 본인 비밀번호로 바꿔서 실행
    # HikariCP?? ?????? ??? ??
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      pool-name: springHikariCP
  # log ??
  messages:
    encoding: UTF-8


  jpa:
    open-in-view: false
    show-sql: true # ??? SQL ??
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        ues_sql_comments: true

image:
  upload:
    dir: src/main/resources/static/boardImages
  access:
    url: /boardImages

server:
  port: 8080
